var GetSkillsResponse_Skills = {
  "_links": {
    "self": "",
    "next": "",
    "previous": ""
  },
  "businessUnitId": 0,
  "lastPollTime": "",
  "totalRecords": 0,
  "skills": [
    {
      "skillId": 0,
      "skillName": "",
      "mediaTypeId": 0,
      "mediaTypeName": "",
      "isActive": true,
      "campaignId": 0,
      "campaignName": "",
      "notes": "",
      "acwTypeId": 0,
      "stateIdACW": 0,
      "stateNameACW": "",
      "maxSecondsACW": 0,
      "acwPostTimeoutStateId": 0,
      "acwPostTimeoutStateName": "",
      "requireDisposition": true,
      "allowSecondaryDisposition": true,
      "scriptDisposition": true,
      "agentRestTime": 0,
      "makeTranscriptAvailable": true,
      "transcriptFromAddress": "",
      "displayThankyou": true,
      "thankYouLink": "",
      "popThankYou": true,
      "popThankYouURL": "",
      "isOutbound": true,
      "outboundStrategy": "",
      "isRunning": true,
      "priorityBlending": true,
      "callerIdOverride": "",
      "scriptId": 0,
      "scriptName": "",
      "emailFromAddress": "",
      "emailFromEditable": true,
      "emailBccAddress": "",
      "emailParking": true,
      "chatWarningThreshold": 0,
      "agentTypingIndicator": true,
      "patronTypingPreview": true,
      "interruptible": true,
      "callSuppressionScriptId": 0,
      "reskillHours": 0,
      "reskillHoursName": "",
      "countReskillHours": true,
      "minWFIAgents": 0,
      "useScreenPops": true,
      "screenPopTriggerEvent": "",
      "useCustomScreenPops": true,
      "screenPopDetail": "",
      "minWorkingTime": 0,
      "agentless": true,
      "agentlessPorts": 0,
      "initialPriority": 0,
      "acceleration": 0,
      "maxPriority": 0,
      "serviceLevelThreshold": 0,
      "serviceLevelGoal": 0,
      "enableShortAbandon": true,
      "shortAbandonThreshold": 0,
      "countShortAbandons": true,
      "countOtherAbandons": true,
      "messageTemplateId": 0,
      "smsTransportCodeId": 0,
      "smsTransportCode": "",
      "dispositions": [
        {
          "dispositionId": 0,
          "dispositionName": "",
          "priority": 0,
          "isPreviewDisposition": true
        }
      ],
      "deliverMultipleNumbersSerially": true,
      "cradleToGrave": true,
      "priorityInterrupt": true
    }
  ]
};