export var GetScheduleSettingsSkillResponse_Skills = {
  "isScheduled": true,
  "sundayStartTime": "",
  "sundayEndTime": "",
  "sundayIsActive": true,
  "mondayStartTime": "",
  "mondayEndTime": "",
  "mondayIsActive": true,
  "tuesdayStartTime": "",
  "tuesdayEndTime": "",
  "tuesdayIsActive": true,
  "wednesdayStartTime": "",
  "wednesdayEndTime": "",
  "wednesdayIsActive": true,
  "thursdayStartTime": "",
  "thursdayEndTime": "",
  "thursdayIsActive": true,
  "fridayStartTime": "",
  "fridayEndTime": "",
  "fridayIsActive": true,
  "saturdayStartTime": "",
  "saturdayEndTime": "",
  "saturdayIsActive": true
};