export var GetOutboundSkillGeneralSettingsResponse_Skills = {
  "minimumRetryMinutes": 0,
  "maximumAttempts": 0,
  "defaultContactExpiration": 0,
  "getPriorityContactsOnContactInsertion": true,
  "loadCallbacks": true,
  "loadFresh": true,
  "loadNonFresh": true,
  "overrideBusinessUnitAbandonRate": true,
  "maximumRingingDuration": 0,
  "beginDampenPercentage": 0,
  "abandonRateCutoff": 0,
  "abandonRateThreshold": 0,
  "inactiveBlenderTimer": 0,
  "maximumRatio": 0,
  "aggressiveness": "",
  "endOfListNotificationsDelay": 0,
  "notifyAgentsWhenListIsEmpty": true,
  "percentageOfAgentsBeforeOverdial": 0,
  "blockMultipleCalls": true,
  "consecutiveAttemptsWithoutALiveConnect": 0,
  "enableDialingByProficiency": true,
  "proficiencyFactor": 0,
  "waitTimeFactor": 0,
  "maxConcurrentCallsPerAgent": 0,
  "maxWaitTimeSeconds": 0
};