export var UpdateSkillRequest_Skills = {
  "skill": {
    "skillName": "",
    "campaignId": 0,
    "callerIdOverride": "",
    "emailFromAddress": "",
    "emailFromEditable": true,
    "emailBccAddress": "",
    "scriptId": 0,
    "reskillHours": 0,
    "minWfiAgents": 0,
    "minWfiAvailableAgents": 0,
    "interruptible": true,
    "enableParking": true,
    "minWorkingTime": 0,
    "agentless": true,
    "agentlessPorts": 0,
    "notes": "",
    "acwTypeId": 0,
    "requireDisposition": true,
    "allowSecondaryDisposition": true,
    "scriptDisposition": true,
    "stateIdAcw": 0,
    "maxSecondsAcw": 0,
    "agentRestTime": 0,
    "displayThankYou": true,
    "thankYouLink": "",
    "popThankYou": true,
    "popThankYouUrl": "",
    "makeTranscriptAvailable": true,
    "transcriptFromAddress": "",
    "priorityBlending": true,
    "callSuppressionScriptId": 0,
    "useScreenPops": true,
    "screenPopTriggerEvent": 0,
    "useCustomScreenPops": true,
    "screenPopType": "",
    "screenPopDetails": "",
    "initialPriority": 0,
    "acceleration": 0,
    "maxPriority": 0,
    "serviceLevelThreshold": 0,
    "serviceLevelGoal": 0,
    "enableShortAbandon": true,
    "shortAbandonThreshold": 0,
    "countShortAbandons": true,
    "countOtherAbandons": true,
    "chatWarningThreshold": 0,
    "agentTypingIndicator": true,
    "smsTransportCodeId": 0,
    "messageTemplateId": 0,
    "dispositions": [
      {
        "dispositionId": 0,
        "priority": 0
      }
    ]
  }
};